### ISSUE TITLE
Put axis scales on Shiny MDS plot

### ISSUE THREAD

**Issue by MichelleKendall** [thibautjombart/treescape#16]
At the moment we have gridlines but no numbers

**Comment by thibautjombart** [comment]
This is a basic convention in ade4 - grid + size indicator (top right) instead of axes labels. We could add values axes, but might be easier to use other graphical functions altogether. If so, *ggplot2* would be an option. But these need to be customized for ordination methods, and adding inset screeplot is not straightforward. Otherwise we can design our own graphics if we want, but that will involve reinventing the wheel. adegraphics will be out soon (hopefully), shall we wait for it to get better graphical options?

**Comment by MichelleKendall** [comment]
Ok no problem - I hadn't seen the grid and size indicator but that sounds fine. Waiting for adegraphics sounds like a good plan.
