### ISSUE TITLE
Installation dependencies?

### ISSUE THREAD

**Issue by MichelleKendall** [thibautjombart/treescape#44]
I just tried installing treescape on a different computer and the installation failed because Rcpp, adegraphics and RLumShiny were not installed. (Even though I was using the option "install package dependencies".) I wonder if these should be in the "depends" list as well as the "imports" list in the description? Or just something buggy about this computer?!

**Comment by thibautjombart** [comment]
I have seen this in other packages too, annoyingly even when teaching in Glasgow. I think this is related to this: 
https://stat.ethz.ch/pipermail/r-help/2012-May/314363.html
http://r.789695.n4.nabble.com/install-packages-and-dependencies-TRUE-td4682332.html

Suggesting we need to provide a repos when installing the package. Apparently there was a bug with devtools at some point, fixed in the github version, which did not handle dependencies upon installation.

**Comment by thibautjombart** [comment]
I'll handle it. We're tricking R with our shiny app released alongside the package. So it doesn't know about dependencies of the app. May need to post on R-dev.. sigh.

**Comment by thibautjombart** [comment]
Solved (I think)
