### ISSUE TITLE
Package is failing Travis check

### ISSUE THREAD

**Issue by MichelleKendall** [thibautjombart/treescape#63]
I believe this is a temporary problem with Travis which seems to be unable to install phangorn. The package still passes the check locally and on win-builder.

**Comment by thibautjombart** [comment]
I had a similar issue I think, due to a dependency in phangorn being now
missing.


--
Dr Thibaut Jombart
Lecturer, Department of Infectious Disease Epidemiology
Imperial College London
https://sites.google.com/site/thibautjombart/
Twitter: @thibautjombart <https://twitter.com/thibautjombart?lang=en-gb>

**Comment by MichelleKendall** [comment]
Adding 

```
r_binary_packages:
  - phangorn
```

to .travis.yml seems to have done the trick.
